### ISSUE TITLE
opendirL Doesn't Report Failure

### ISSUE THREAD

**Issue by vadim-160102** [rdboisvert/Win32-LongPath#11]
Please see https://metacpan.org/source/RBOISVERT/Win32-LongPath-2.0/lib/Win32/LongPath.pm#L1002

I think that number could be replaced with "~0".

**Comment by rdboisvert** [comment]
I will take a look at it.

**Comment by rdboisvert** [comment]
Fixed return on error issue.

Thank you for reporting this.
