### ISSUE TITLE
_set_perl_err clobbers $!

### ISSUE THREAD

**Issue by andrewgregory** [rdboisvert/Win32-LongPath#2]
Some functions (such as `win32_open_osfhandle`) only set `errno` on failure so `$^E` is `undef`.  Calling `_set_perl_err` after these functions fail makes it impossible for the caller to get the error.  I glanced at the equivalent functions in the PerlIO source and didn't notice any explicit modification of `$!`; does Win32::LongPath actually need to manually set `$!`?

**Comment by rdboisvert** [comment]
Is this error specific to Strawberry Perl?

**Comment by andrewgregory** [comment]
This applies to ActivePerl as well.  Here's a quick test script that relies on #3 to exhaust the available file descriptors and force `win32_open_osfhandle` to fail:

``` perl
use Win32::LongPath;
for ( my $i = 1; $i <= 3_000; $i++ ) {
    Win32::LongPath::openL(\(my $fh), '<', $0)
      or die "attempt $i failed ($!:$^E)";
}
```

Currently this prints:

> attempt 2046 failed (:)

If I comment out the `_set_perl_err()` on line 482 following the call to `create_file` I get:

> attempt 2046 failed (Too many open files:)

**Comment by rdboisvert** [comment]
I adjusted the program to limit the change to the Windows error code and pushed it to master.  I was not able to get your test program to fail with the old or new program.  Can you test the new one and let me know what you find?

Thanks

**Comment by andrewgregory** [comment]
What version of perl were you using?  The bug responsible for #3 was introduced in 5.22; otherwise you may have a higher open file limit than I do, I don't know enough about Windows to know where that limit comes from.  Regardless, following 35462ed, it now gives a useful error message:

> attempt 2045 failed (Too many open files:)

**Comment by rdboisvert** [comment]
Fix released to CPAN.  Closing this bug.
