### ISSUE TITLE
Can't call method "encode" on an undefined value at Win32/LongPath.pm line 1151.

### ISSUE THREAD

**Issue by loctimize** [rdboisvert/Win32-LongPath#5]
When running a compiled script that uses Win32::LongPath 1.0.6 to recursively scan a directory on Windows I get the above mentioned error. Script was compiled on Windows 10 using Strawberry Perl 5.24 and pp. The script itself runs fine when called from the *.pl file. Do you have any idea or suggestion what might cause the issue? I attached the code. 
[readDirsWin.zip](https://github.com/rdboisvert/Win32-LongPath/files/412238/readDirsWin.zip)
Please tell me if you need any additional information.

**Comment by rdboisvert** [comment]
Sorry, I'm not familiar with pp.  If it works in the normal Perl environment but doesn't work with pp you probably want to consult with the author of pp.

**Comment by loctimize** [comment]
Ok, thank you very much. Will do!
