### ISSUE TITLE
expose CreateFileW directly

### ISSUE THREAD

**Issue by andrewgregory** [rdboisvert/Win32-LongPath#7]
I need to be able to create files exclusively (equivalent to `sysopen($fh, $path, O_CREAT|O_EXCL)`).  The Win32::LongPath documentation says that a sysopen interface is not provided because it uses fdopen.  Could Win32::LongPath instead provide a more direct wrapper for CreateFileW to allow specifying the ShareMode and CreationDisposition flags?

**Comment by rdboisvert** [comment]
I will investigate what it takes to do this.

**Comment by rdboisvert** [comment]
The coding and testing are done on my end.  Can you test to see if this is ready for release?  Please note that I made changes that could affect the reference count problem you found before.  Unfortunately, I can't test that part on my system.  Can you verify that it did not break again?

**Comment by rdboisvert** [comment]
Released as v2.0.  Closing issue.
